spring:
  application:
    name: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: he182335@gmail.com
    password: mnxhcfblsmahkcse
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ELN2fFMaizi8pBZNeOd51QDIM2bY1UccIpdSziPgcgSPzZ7Q7YDc5HUzewDnZpN6G7WGJZxKIqKdr3B4dIW37rwfgPYcXzrjyt2VlbmutsOsg15kQEs0No2ZHHYKLWUb2Tksu9wNuGVZkEXJ15pbRecSrOQk8t3aAxgvSyuXxOiv2vmVwx6xteH04B6C2r9Ruj8P1TTgOyIeLGX5XgPuCjNxW3e6fSMLwmSYjKR0p4F8csEolpO7YyVMlpsg4YB4

cloudinary:
  name: do04pnfy1
  api-key: 495814622696344
  api-secret: 5zg7-C_x3XihPYBHu9PK8sfCfIw